trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
# Step 1: Install necessary tools
- task: Bash@3
  displayName: 'Install jq and curl'
  inputs:
    targetType: 'inline'
    script: |
      sudo apt-get update
      sudo apt-get install -y jq curl

# Step 2: Set up environment variables
- task: Bash@3
  displayName: 'Set up environment variables'
  inputs:
    targetType: 'inline'
    script: |
      echo "##vso[task.setvariable variable=TENANT_ID]$(TENANT_ID)"
      echo "##vso[task.setvariable variable=CLIENT_ID]$(CLIENT_ID)"
      echo "##vso[task.setvariable variable=CLIENT_SECRET]$(CLIENT_SECRET)"
      echo "##vso[task.setvariable variable=SHAREPOINT_SITE_URL]$(SHAREPOINT_SITE_URL)"
      echo "##vso[task.setvariable variable=DOCUMENT_LIBRARY]$(DOCUMENT_LIBRARY)"
      echo "##vso[task.setvariable variable=LOCAL_TEMPLATES_PATH]$(Build.SourcesDirectory)/templates"

# Step 3: Run the migration script
- task: Bash@3
  displayName: 'Run Migration Script'
  inputs:
    targetType: 'filePath'
    filePath: './migrate-templates.sh'

# Step 4: Run the validation script
- task: Bash@3
  displayName: 'Validate Migration'
  inputs:
    targetType: 'filePath'
    filePath: './validate-migration.sh'
